apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
spec: 
  replicas: 6
  selector: ##выбор по label
    matchLabels:
      app: my-app
  strategy: ##регламент порядка обновления приложения
    rollingUpdate: 
      maxSurge: 2 ##насколько можно поднять количество реплик при обновлений по сравнению с тем, что задано в replicas(можно в %)
      maxUnavailable: 2 ##при процессе обновления разрешается 1 старую реплику погасить
    type: RollingUpdate    
  template: ##шаблон какие поды создавать
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: nginx:1.13
          name: nginx
          ports:
            - containerPort: 80