apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-replicaset
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: my-app-1
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
        - image: nginx:1.13
          name: nginx
          ports:
            - containerPort: 80